"""agrega nrodoc en contactos

Revision ID: a90cd1db487c
Revises: 3ad9f66cef40
Create Date: 2024-07-10 19:18:57.261357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90cd1db487c'
down_revision: Union[str, None] = '3ad9f66cef40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactos', sa.Column('nrodoc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contactos', 'nrodoc')
    # ### end Alembic commands ###
